const DEFAULT_M3U="https://iptv-org.github.io/iptv/countries/th.m3u";
const $=s=>document.querySelector(s);
let channels=[],cat="ทั้งหมด",view="all",fav=new Set(JSON.parse(localStorage.getItem("tvFav")||"[]")),hls=null,epg={};
const cats=["ทั้งหมด","รายการโปรด","ข่าว","ทั่วไป","บันเทิง","กีฬา","การศึกษา","ภาพยนตร์","ศาสนา","เพลง"];

function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function parseM3U(t){let a=[],m=null;for(let l of t.split(/\r?\n/)){l=l.trim();if(!l)continue;if(l.startsWith("#EXTINF")){m=l;continue}if(!l.startsWith("#")&&m){let name=(m.match(/,(.*)$/)||[])[1]||"Unknown",logo=(m.match(/tvg-logo="([^"]*)"/)||[])[1]||"",group=(m.match(/group-title="([^"]*)"/)||[])[1]||"ทั่วไป",id=(m.match(/tvg-id="([^"]*)"/)||[])[1]||"";a.push({name:name.trim(),logo,url:l,group,id});m=null}}return a}
function group(g,n){let s=(g+" "+n).toLowerCase();if(/news|ข่าว/.test(s))return"ข่าว";if(/sport|กีฬา/.test(s))return"กีฬา";if(/entertain|บันเทิง|variety/.test(s))return"บันเทิง";if(/education|การศึกษา/.test(s))return"การศึกษา";if(/movie|film|ภาพยนตร์/.test(s))return"ภาพยนตร์";if(/relig|ศาสนา/.test(s))return"ศาสนา";if(/music|เพลง/.test(s))return"เพลง";return"ทั่วไป"}
function tabs(){ $("#tabs").innerHTML=cats.map(x=>`<button class="tab ${cat===x?"active":""}" data-c="${x}">${x}</button>`).join("");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{cat=b.dataset.c;view=cat==="รายการโปรด"?"fav":"all";render()})}
function list(){let a=channels;if(view==="fav")a=a.filter(x=>fav.has(x.url));if(cat!=="ทั้งหมด"&&cat!=="รายการโปรด")a=a.filter(x=>x.cat===cat);let q=$("#search").value.trim().toLowerCase();if(q)a=a.filter(x=>(x.name+" "+x.group).toLowerCase().includes(q));return a}
function render(){tabs();let a=list();$("#title").textContent=view==="fav"?"รายการโปรด":cat==="ทั้งหมด"?"ช่องทั้งหมด":cat;$("#count").textContent=a.length+" ช่อง";$("#grid").innerHTML=a.length?a.map((x,i)=>`<article class="card" data-i="${i}"><div class="thumb">${x.logo?`<img src="${esc(x.logo)}" onerror="this.style.display='none'">`:""}<div class="fallback" ${x.logo?'style="display:none"':''}>TV</div><span class="live">LIVE</span><button class="star" data-star="${encodeURIComponent(x.url)}">${fav.has(x.url)?"★":"☆"}</button></div><div class="info"><div class="name">${esc(x.name)}</div><div class="meta"><span>${esc(x.cat)}</span><span>${epg[x.id]?.title? "EPG":""}</span></div></div></article>`).join(""):`<div class="empty">ไม่พบช่องในหมวดนี้</div>`;document.querySelectorAll(".card").forEach(c=>c.onclick=e=>{if(e.target.closest(".star"))return;open(a[+c.dataset.i])});document.querySelectorAll("[data-star]").forEach(b=>b.onclick=e=>{e.stopPropagation();let u=decodeURIComponent(b.dataset.star);fav.has(u)?fav.delete(u):fav.add(u);localStorage.setItem("tvFav",JSON.stringify([...fav]));render()})}
async function load(url=localStorage.getItem("tvM3U")||DEFAULT_M3U){$("#status").textContent="กำลังโหลดช่อง…";try{let r=await fetch(url);if(!r.ok)throw Error("HTTP "+r.status);channels=parseM3U(await r.text()).map(x=>({...x,cat:group(x.group,x.name)}));localStorage.setItem("tvM3U",url);$("#status").textContent=`พร้อมใช้งาน • ${channels.length} ช่อง`;render()}catch(e){$("#status").textContent="โหลด Playlist ไม่สำเร็จ";$("#grid").innerHTML=`<div class="empty">โหลดไม่ได้<br><small>${esc(e.message)}</small></div>`}}
async function loadEPG(url){if(!url)return;try{let r=await fetch(url);if(!r.ok)throw Error();let t=await r.text(),xml=new DOMParser().parseFromString(t,"text/xml");xml.querySelectorAll("programme").forEach(p=>{let id=p.getAttribute("channel"),title=p.querySelector("title")?.textContent||"",desc=p.querySelector("desc")?.textContent||"",start=p.getAttribute("start")||"",stop=p.getAttribute("stop")||"";if(id&&!epg[id])epg[id]={title,desc,start,stop}});render()}catch(e){toast("โหลด EPG ไม่สำเร็จ")}}
function currentProgram(c){let p=epg[c.id];if(!p)return null;let now=Date.now(),s=Date.parse(p.start),e=Date.parse(p.stop);return isNaN(s)||isNaN(e)||now<s||now>e?null:p}
function open(c){$("#player").classList.add("show");$("#ptitle").textContent=c.name;let p=currentProgram(c);$("#nowTitle").textContent=p?.title||"กำลังเล่น";$("#nowDesc").textContent=p?.desc||c.cat;let v=$("#video");if(hls){hls.destroy();hls=null}v.src="";if(window.Hls&&Hls.isSupported()&&/\.m3u8($|\?)/i.test(c.url)){hls=new Hls();hls.loadSource(c.url);hls.attachMedia(v);hls.on(Hls.Events.MANIFEST_PARSED,()=>v.play().catch(()=>{}))}else{v.src=c.url;v.play().catch(()=>{})}}
$("#close").onclick=()=>{let v=$("#video");v.pause();v.removeAttribute("src");v.load();if(hls){hls.destroy();hls=null}$("#player").classList.remove("show")};
$("#pip").onclick=async()=>{try{if(document.pictureInPictureEnabled&&!$("#video").disablePictureInPicture)await $("#video").requestPictureInPicture()}catch(e){toast("อุปกรณ์นี้ไม่รองรับ PiP")}};
$("#air").onclick=()=>{if($("#video").webkitShowPlaybackTargetPicker)$("#video").webkitShowPlaybackTargetPicker();else toast("AirPlay ใช้ได้บน Safari/iOS ที่รองรับ")};
$("#search").oninput=render;$("#refresh").onclick=()=>load();
$("#settings").onclick=()=>{$("#playlist").value=localStorage.getItem("tvM3U")||DEFAULT_M3U;$("#epg").value=localStorage.getItem("tvEPG")||"";$("#modal").classList.add("show")};
$("#cancel").onclick=()=>$("#modal").classList.remove("show");
$("#save").onclick=()=>{let m=$("#playlist").value.trim()||DEFAULT_M3U,e=$("#epg").value.trim();localStorage.setItem("tvM3U",m);localStorage.setItem("tvEPG",e);$("#modal").classList.remove("show");load(m);if(e)loadEPG(e)};
document.querySelectorAll(".bottom button[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;cat=view==="fav"?"รายการโปรด":"ทั้งหมด";document.querySelectorAll(".bottom button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#install").hidden=false});$("#install").onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
load();if(localStorage.getItem("tvEPG"))loadEPG(localStorage.getItem("tvEPG"));
